//
// Created by Leti on 17.05.2022.
//

#ifndef LAB9_COPIE_COPIE_COPIE_MONEYSERVICETESTS_H
#define LAB9_COPIE_COPIE_COPIE_MONEYSERVICETESTS_H

void testAddMoney();

#endif //LAB9_COPIE_COPIE_COPIE_MONEYSERVICETESTS_H
